version: '3'
services:
  app-static:
    image: svelte-docker-static
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-static
    ports:
      - 3001:80

  app-node:
    image: svelte-docker-node
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node
    ports:
      - 3002:3000
